version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running Django unit tests
      - python manage.py test
  post_build:
    commands:
      - echo Build and test completed on `date`
